import = [
  "/Users/capitanbobo/.config/alacritty/themes/monokai.toml",
  "/Users/capitanbobo/.config/alacritty/themes/catppuccin-frappe.toml"
]
working_directory = "None"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mode = "~Search"
mods = "Alt"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"
option_as_alt = 'Both'